### PR TITLE
refactor: replace `get(0)` with cleaner `first()`

### PR DESCRIPTION
**Pull request by hamirmahal**

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
Most of the changes in this pull request are from formatting.

We should probably leverage `cargo fmt` to reduce noise in `diff`s.

**Comment by xlmnxp** [comment]
@hamirmahal I agree with you, I will add something like Code Lint to force the format

**Comment by xlmnxp** [comment]
also, thank you for your contribution :+1:

**Comment by hamirmahal** [comment]
You're welcome!

**Pull request merged**
