### PR TITLE
Initial gtk4 migration

### PR DESCRIPTION
**Pull request by ochibani**
I tried to minimize code changes it's not working yet, but can be a good starting point.
The window size is not the same as the gtk3 version, probably something wrong in main.ui file.
FileChooserButton not the same as the gtk3 we can make it look and act the same as old version, but I don't think this is useful.
We need to replace Appindicator

### CODE REVIEW

**Comment by xlmnxp** [comment]
I suggest to remove libappindicator support

**Comment by ochibani** [comment]
I believe we need to do this tasks to have working X11 version.
Stable X11 version:
- [ ]  Fix progress dialog (“not doing its job correctly”).
- [ ]  Fix play button (“xdg-open return no such file or directory”).
- [ ] Fix some Gtk messages related to “main.ui”.
- [ ] Fix is_file_already_exists function.
- [ ] Return missing video formats to combo box.
- [ ] Add indicator functionality
- [ ] Add timer to header bar.

**Comment by ochibani** [comment]
Select a Window is not supported in Wayland due to security measures.

**Comment by xlmnxp** [comment]
@ochibani that wired
I know discord, slack, brave and others support select window

**Comment by ochibani** [comment]
Audio recording not working in old version gtk3 due to how record button function works, so I removed the audio only record functionality as it's not core functionality for blue recorder.

**Comment by xlmnxp** [comment]
@ochibani don't merge, still there issue with Clone derive for Std::Process::Child

**Comment by xlmnxp** [comment]
Thank you, I will merge your changes

**Pull request merged**
