### PR TITLE
Add zh_Hans.po (Chinese Simplified) to po directory

### PR DESCRIPTION
**Pull request by larryw3i**
Add zh_Hans.po to po directory, by the way, running "cargo build --release" doesn't work for me, the version of dependencies.gio is not specified.
Screenshot from 2021-08-10 07-34-27

### CODE REVIEW

**Comment by xlmnxp** [comment]
you can run it by 
```
cargo run
```

**Comment by larryw3i** [comment]
> you can run it by
> 
> ```
> cargo run
> ```

Buddy, It still crashs.
```
$ cargo run
error: failed to parse manifest at `/home/larry/fun/larryw3i/blue-recorder/Cargo.toml`

Caused by:
  failed to parse the version requirement `` for dependency `gio`

Caused by:
  unexpected end of input while parsing major version number
```
How do I solve it?

**Comment by larryw3i** [comment]
> you can run it by
> 
> ```
> cargo run
> ```

https://github.com/xlmnxp/blue-recorder/blob/master/Cargo.toml#L26#L28
Don't we need a version of gio?

**Comment by larryw3i** [comment]
@xlmnxp  Thank you, It works for me now.

Screenshot from 2021-08-10 18-03-51

**Comment by xlmnxp** [comment]
> @xlmnxp Thank you, It works for me now.
> 
> Screenshot from 2021-08-10 18-03-51

Can you commit the changes in Cargo.toml?

**Comment by larryw3i** [comment]
> > @xlmnxp Thank you, It works for me now.
> > Screenshot from 2021-08-10 18-03-51
> 
> thank you
> Can you commit the changes in Cargo.toml?

I have committed it.
https://github.com/xlmnxp/blue-recorder/pull/21/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R27

**Comment by larryw3i** [comment]
zh_CN is much the same as zh_Hans, so I submitted zh_CN.po as well.

**Comment by larryw3i** [comment]
But It seems that multilingual feature still doesn't work for me yet. I don't know how to test it.
Screenshot from 2021-08-10 21-02-37

**Comment by xlmnxp** [comment]
> But It seems that multilingual feature still doesn't work for me. I don't know how to test it.
> Screenshot from 2021-08-10 21-02-37

I will fix it soon, thank you from your contribution
it will make blue recorder better

**Pull request merged**
