### PR TITLE
Draft: Appdata and translation related patches

### PR DESCRIPTION
**Pull request by sabriunal**
- Add translator-credits support
- Fix a few appdata strings
- Update the POT file

I coldn't build the patch (yet)

### CODE REVIEW

**Comment by xlmnxp** [comment]
Can you tell me what issue you facing in building of Blue Recorder?

**Comment by sabriunal** [comment]
Translations seem missing. UI seem untranslated.

**Comment by xlmnxp** [comment]
> Translations seem missing. UI seem untranslated.

correct, we are facing some issues with `gettext`
#10

**Comment by sabriunal** [comment]
There was no translation and no activity related to translated po files. I'm not expert on Meson but there is no meson file to build the po files.

amberol 
meson.build file 
in main folder: https://gitlab.gnome.org/World/amberol/-/blob/main/meson.build?ref_type=heads
in po directory: https://gitlab.gnome.org/World/amberol/-/blob/main/po/meson.build?ref_type=heads
gettext binding: https://gitlab.gnome.org/World/amberol/-/blob/main/src/main.rs?ref_type=heads#L44

**Comment by xlmnxp** [comment]
we don't need meson, cargo handle the build process

**Comment by sabriunal** [comment]
Sorry. My knowledge is limited. Thanks for your pation.

**Comment by sabriunal** [comment]
simple version of this patch: https://github.com/xlmnxp/blue-recorder/pull/51

**Pull request closed without merging**
